### ISSUE TITLE
Game titles don't appear

### ISSUE THREAD

**Issue by arxnaldo** [RedSchism/ubiquity#1]
I found this theme very cool and elegant. But for some reason on my laptop the game titles don't appear as in the screenshot I saw on Playnite. I've tried all the available settings and nothing has solved my problem. How can I make it look as good as the screenshots?

![Screenshot (12)](https://github.com/RedSchism/ubiquity/assets/51685889/19738ac3-4f2d-4c09-a183-b91d77e6fbcb)
![Screenshot (13)](https://github.com/RedSchism/ubiquity/assets/51685889/96c8f391-99e7-4a20-aa82-aa6184df1e6e)

**Comment by RedSchism** [comment]
You need the "Extra Metadata Loader" add-on.  It's in the Playnite Add-Ons Menu. Under Add-Ons>Browse>Generic.
