### ISSUE TITLE
Background changer integration

### ISSUE THREAD

**Issue by ghost** [RedSchism/ubiquity#10]
Any way to display animated cover images and backgrounds in the theme?

**Comment by RedSchism** [comment]
There is currently no way to use animated covers in Playnite.  As for animated backgrounds you could use the extra metadata add-on and replace the game trailers / microtrailer with an animated backgrounds, if you can find/make them in .mp4 format.

**Comment by ghost** [comment]
Got it, thank you very much for the info!

**Comment by ghost** [comment]
Btw. just so its clear are you referring to the Fullscreen mode only, because using the background changer addon I can get animated covers and backgrounds in desktop mode, I looked through the addons github issues and I found one post where the addon had to be added somehow in the theme to support it. I should probably ask there then. Still thanks.

**Comment by RedSchism** [comment]
Yes, I was referring to fullscreen mode.

I've never used background changer but yes, as that post suggested add-on support would have to be hard coded into a theme.
