### ISSUE TITLE
Ultrawide issue.  The "settings button" is not where it's supposed to be

### ISSUE THREAD

**Issue by planet** [RedSchism/ubiquity#4]
![image](https://github.com/RedSchism/ubiquity/assets/1265868/8537948b-fd3d-449c-af8b-8533c4756aa1)

**Comment by planet** [comment]
Also an issue on 16x10 screen. I can't find the "circle" at all.

**Comment by RedSchism** [comment]
Thank you for bringing this to my attention. A fix for this among other issues will be released soon!

**Comment by planet** [comment]
> Thank you for bringing this to my attention. A fix for this among other issues will be released soon!

Great, hope to see the update soon!
