### ISSUE TITLE
Enhancement Request: Clarify Documentation for Customizing Filter Icons

### ISSUE THREAD

**Issue by zeedif** [RedSchism/ubiquity#7]
First of all, I want to express my appreciation for your work on the (u)biquity theme, which I have been using and enjoying. However, as a new Playnite user, I encountered a minor difficulty when trying to customize filter icons, and I believe additional information in the documentation could be helpful for other novice users. Initially, I assumed that customizing filter icons would be done in the Playnite Desktop user interface. Still, after navigating through the theme code, I realized that the filter name is actually concatenated to the images in the FilterIcons folder.

Currently, there is no information in the Readme explaining how to customize filter icons. After some exploration, I discovered that it is possible to add new PNG images to the Images/Icons/FilterIcons folder or rename existing images to use them for localized filters (I'm from Mexico and wanted to have the filters in Spanish, but the icons weren't showing). I believe it would be beneficial to add a section in the Readme that clearly explains this process.

## Example

![image](https://github.com/RedSchism/ubiquity/assets/60901341/7e2596ec-d201-426d-968a-7c31379a772a)

**Comment by RedSchism** [comment]
Thank you!
 
I've just updated the ReadMe to include entries for Filter Customization, Filter Sorting, as well as Basic Controls. I will also be adding default playnite filter icons for multiple languages in the next update.
Hopefully these changes and additions will improve the new user experience going forward.
